require('dotenv').config();
const express=require('express'); const session=require('express-session'); const multer=require('multer'); const Database=require('better-sqlite3'); const nodemailer=require('nodemailer'); const path=require('path'); const fs=require('fs');
const app=express(); const PORT=process.env.PORT||3000;
const dataDir=path.join(__dirname,'data'), uploadDir=path.join(__dirname,'uploads'); fs.mkdirSync(dataDir,{recursive:true}); fs.mkdirSync(uploadDir,{recursive:true});
const db=new Database(path.join(dataDir,'site.db')); db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS requests(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL,email TEXT NOT NULL,type TEXT,plan TEXT,deadline TEXT,budget TEXT,message TEXT,filename TEXT,originalname TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,status TEXT DEFAULT 'new')`);
app.use(express.urlencoded({extended:true})); app.use(session({secret:process.env.SESSION_SECRET||'dev-secret-change-me',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:false,maxAge:8*60*60*1000}}));
app.use(express.static(path.join(__dirname,'public')));
const allowed=['.mp4','.mov','.m4v','.avi','.mkv','.webm']; const storage=multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>cb(null,Date.now()+'-'+Math.random().toString(36).slice(2)+path.extname(file.originalname).toLowerCase())});
const upload=multer({storage,limits:{fileSize:2*1024*1024*1024},fileFilter:(req,file,cb)=>allowed.includes(path.extname(file.originalname).toLowerCase())?cb(null,true):cb(new Error('動画ファイルは mp4 / mov / m4v / avi / mkv / webm のみ対応です。'))});
function auth(req,res,next){if(req.session.admin)return next(); res.redirect('/admin/login');}
async function notify(r){ if(!process.env.SMTP_HOST||!process.env.NOTIFY_EMAIL)return; const t=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE)==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}); await t.sendMail({from:process.env.SMTP_USER,to:process.env.NOTIFY_EMAIL,subject:`【動画編集依頼】${r.name}様から新規依頼`,text:`新しい依頼が届きました。\n\nお名前: ${r.name}\nメール: ${r.email}\n種類: ${r.type}\nプラン: ${r.plan}\n納期: ${r.deadline}\n予算: ${r.budget}\nファイル: ${r.originalname||'なし'}\n\n内容:\n${r.message}\n\n管理画面: /admin`});}
app.post('/api/requests',upload.single('video'),async(req,res)=>{try{const r={...req.body,filename:req.file?.filename||'',originalname:req.file?.originalname||''}; if(!r.name||!r.email||!r.message)throw Error('必須項目が不足しています。'); const info=db.prepare('INSERT INTO requests(name,email,type,plan,deadline,budget,message,filename,originalname) VALUES(?,?,?,?,?,?,?,?,?)').run(r.name,r.email,r.type||'',r.plan||'',r.deadline||'',r.budget||'',r.message,r.filename,r.originalname); r.id=info.lastInsertRowid; try{await notify(r)}catch(e){console.error('Email notification failed:',e.message)} res.send('<!doctype html><meta charset="utf-8"><title>送信完了</title><link rel="stylesheet" href="/style.css"><main class="result"><div class="result-card"><p class="eyebrow">THANK YOU</p><h1>お問い合わせを受け付けました。</h1><p>ご依頼内容を確認のうえ、担当者からご連絡します。</p><a class="btn primary" href="/">トップへ戻る</a></div></main>')}catch(e){res.status(400).send('<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/style.css"><main class="result"><div class="result-card"><h1>送信できませんでした</h1><p>'+String(e.message).replace(/[<>]/g,'')+'</p><a class="btn secondary" href="/">戻る</a></div></main>')}});
app.get('/admin/login',(req,res)=>res.send(`<!doctype html><meta charset="utf-8"><title>管理画面ログイン</title><link rel="stylesheet" href="/style.css"><main class="result"><form class="login-card" method="post"><p class="eyebrow">ADMIN</p><h1>管理画面</h1><label>パスワード<input type="password" name="password" required autofocus></label><button class="btn primary submit">ログイン</button></form></main>`));
app.post('/admin/login',(req,res)=>{if(req.body.password && req.body.password===(process.env.ADMIN_PASSWORD||'admin')){req.session.admin=true;res.redirect('/admin')}else res.status(401).send('<p>パスワードが違います。<a href="/admin/login">戻る</a></p>')});
app.post('/admin/logout',auth,(req,res)=>req.session.destroy(()=>res.redirect('/')));
app.get('/admin',auth,(req,res)=>{const rows=db.prepare('SELECT * FROM requests ORDER BY id DESC').all(); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); const list=rows.map(r=>`<article class="request"><div class="request-top"><div><span class="status">${esc(r.status)}</span><h2>#${r.id} ${esc(r.name)}</h2><p>${esc(r.created_at)} · <a href="mailto:${esc(r.email)}">${esc(r.email)}</a></p></div><form method="post" action="/admin/status"><input type="hidden" name="id" value="${r.id}"><select name="status"><option ${r.status==='new'?'selected':''}>new</option><option ${r.status==='in_progress'?'selected':''}>in_progress</option><option ${r.status==='done'?'selected':''}>done</option></select><button>更新</button></form></div><div class="request-grid"><p><b>種類</b><br>${esc(r.type)}</p><p><b>プラン</b><br>${esc(r.plan)}</p><p><b>納期</b><br>${esc(r.deadline)}</p><p><b>予算</b><br>${esc(r.budget)}</p></div><p class="message">${esc(r.message).replace(/\n/g,'<br>')}</p>${r.filename?`<p>📎 <a href="/admin/files/${encodeURIComponent(r.filename)}">${esc(r.originalname)}</a></p>`:''}</article>`).join(''); res.send(`<!doctype html><meta charset="utf-8"><title>依頼管理</title><link rel="stylesheet" href="/style.css"><header class="header"><a class="logo" href="/">EDIT LAB</a><div>管理画面 <form style="display:inline" method="post" action="/admin/logout"><button class="logout">ログアウト</button></form></div></header><main class="admin"><div class="admin-head"><div><p class="eyebrow">DASHBOARD</p><h1>依頼管理</h1><p>${rows.length}件の依頼</p></div><a class="btn secondary" href="/">サイトを見る</a></div>${list||'<div class="empty">まだ依頼はありません。</div>'}</main>`) });
app.post('/admin/status',auth,(req,res)=>{db.prepare('UPDATE requests SET status=? WHERE id=?').run(req.body.status,req.body.id);res.redirect('/admin')});
app.get('/admin/files/:name',auth,(req,res)=>{const safe=path.basename(req.params.name); const f=path.join(uploadDir,safe); if(!fs.existsSync(f))return res.sendStatus(404);res.download(f)});
app.use((err,req,res,next)=>{console.error(err);res.status(400).send('<p>'+String(err.message).replace(/[<>]/g,'')+'</p><p><a href="/">戻る</a></p>')});
app.listen(PORT,()=>console.log(`EDIT LAB running on http://localhost:${PORT}`));
